### ISSUE TITLE
Re-establish quant server. : docker vs cubernetes, hosting vs AWS, goals of rapid development etc.

### ISSUE THREAD

**Issue by nikolas-joyce** [TMQR/SG#1]
I need to deploy a quant server with the previous functionality. I will need to design alphas, deploy alphas, construct campaigns and publish trades, positions, performance, and cost information.  Option data may not be required initially just futures and later ETF data.

Comments on different deployment options would be appreciated.  AWS vs. dedicated.  Hosted MongoDB vs dedicated DB Server.
I have also looked at https://www.floydhub.com/
I would like to have the ability to deploy/ clone server setup for alternate use cases.

**Comment by nikolas-joyce** [comment]
Further to our conversation, I would like to have the following packages available in addition to the ubiquitous pandas, numpy, bokeh, seaborn, scipy

bt
ffn
jhtalib or talib if possible
pyti
quandl
tiingo
monthly_returns_heatmap
alpha_vantage.
tensorflow.

I uploaded a couple of sample notebooks that contain the primary TMQR libraries here 
https://github.com/TMQR/TMQR_Global_Macro_Indexes.

it looks like these are the main libraries I used.

import sys,os
from backtester.analysis import *
from backtester.swarms.swarm import Swarm
from backtester.exoinfo import EXOInfo
from exobuilder.data.exostorage import EXOStorage

have a look at the note books requirements by going here.
https://colab.research.google.com/drive/
then  select GITHUB
then enter this address:
https://github.com/TMQR/TMQR_Global_Macro_Indexes/blob/master/Bucephalus_Crude_Oil_Index_Returns.ipynb

You can view the required libraries without running the notebook.

**Comment by alexveden** [comment]
@nikolas-joyce 

At the initial step I can implement the following steps:
1. Setup new AWS Ubuntu Linux server from scratch (firewalls, ssh, users config)
2. Install VPN (new keys)
3. Install Python and libs 
4. Install Jupyter notebook server (Brand new Jupyter Lab https://jupyterlab.readthedocs.io/en/stable/)
5. Recover MongoDB from your dump
6. Install TMQR V1 and V2 stuff (DBs, code, notebooks, etc) from the GitHub

As the result, you will get a quant server with old DB, but you will be capable to backtest alphas, build campaigns and deploy them.

p.s. As I remember, the old server used old pandas version 0.18, a current version is 0.23. The problem, that the quotes inside the MongoDB for V2 are stored in the special binary format that fails after Pandas upgrade 0.20+, I could make a converter for the new version of Pandas. However, this could lead to the cascade of code compatibility issues, generally to deprecation warnings. You could use old Pandas as well, but compatibility issues will grow with time, this will make upgrading more complex. We can structure this as a standalone milestone.

**Comment by nikolas-joyce** [comment]
This sounds good. It is probably ok to put the pandas issue down the road but I would like to make the upgrade and maintenance process as clean as possible .

Sent from my iPhone

On Jan 8, 2019, at 7:22 AM, Aleksandr Vedeneev <notifications@github.com<mailto:notifications@github.com>> wrote:


@nikolas-joyce<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnikolas-joyce&data=02%7C01%7C%7C4572c00ab9c9496a35bf08d6757d1970%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636825577482757913&sdata=mHGmPXZa%2B%2FAiHMi8hGjnsYr7giMemCp5srFWYB6H9d8%3D&reserved=0>

At the initial step I can implement the following steps:

  1.  Setup new AWS Ubuntu Linux server from scratch (firewalls, ssh, users config)
  2.  Install VPN (new keys)
  3.  Install Python and libs
  4.  Install Jupyter notebook server (Brand new Jupyter Lab https://jupyterlab.readthedocs.io/en/stable/<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjupyterlab.readthedocs.io%2Fen%2Fstable%2F&data=02%7C01%7C%7C4572c00ab9c9496a35bf08d6757d1970%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636825577482757913&sdata=x29Ar5R5fl%2F3VWM6RG%2Fq8XbaEpx4Q91OPbEGeFbWrUk%3D&reserved=0>)
  5.  Recover MongoDB from your dump
  6.  Install TMQR V1 and V2 stuff (DBs, code, notebooks, etc) from the GitHub

As the result, you will get a quant server with old DB, but you will be capable to backtest alphas, build campaigns and deploy them.

p.s. As I remember, the old server used old pandas version 0.18, a current version is 0.23. The problem, that the quotes inside the MongoDB for V2 are stored in the special binary format that fails after Pandas upgrade 0.20+, I could make a converter for the new version of Pandas. However, this could lead to the cascade of code compatibility issues, generally to deprecation warnings. You could use old Pandas as well, but compatibility issues will grow with time, this will make upgrading more complex. We can structure this as a standalone milestone.
