### ISSUE TITLE
Add a group of futures products with history to V1

### ISSUE THREAD

**Issue by nikolas-joyce** [TMQR/SG#2]
I will add a repository for this task with the description:

Futures products to add	
Soybean Meal	
Hang Seng Index futures	HK
Topix Index futures	TSE
Nikkei Index futures	SGX
MSCI Taiwan	SGX
AEX Index	Euronext
CAC 40	Euronext
DAX	Eurex
FTSE 100 	ICE Liffe
Euro Stoxx50	Eurex
Euro-OAT Futures (FOAT) Eurex
Long-Term Euro-BTP Futures (FBTP)
VSTOXX Eurex
VIX futures CFE
Dollar Index	ICE 
Mexican Peso	CME
Swiss Franc	CME
Bobl	Eurex
Bund	Eurex
Russell 2000 Futures	CME/ ICE
Midcap 600 Futures	CME
NASDAQ 100 Futures	CME
Dow Jone Industrials Futures	CME

MSCI Emerging Markets Index futures ICE

**Select sector futures**
https://www.cmegroup.com/trading/equity-index/select-sector-index.html

Brent Crude ICE
Gasoil ICE
RBOB NYMEX
Heating Oil NYMEX

Let's consider https://www.quantgo.com/ for new data needs possibly.

**Comment by alexveden** [comment]
I'm not sure about quantgo, maybe they offering only remote access to the data without download possibility. This is my guess...

**Comment by nikolas-joyce** [comment]
I was thinking we could create the exo in the quantgo environment or backtest an alpha there. If I am happy with what I find then we can download the result either the exo or the strategy context. We could then just use a different real-time data source to incrementally update the exo based on the percentage change.

Sent from my iPhone

On Jan 23, 2019, at 1:41 AM, Aleksandr Vedeneev <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure about quantgo, maybe they offering only remote access to the data without download possibility. This is my guess...
