### ISSUE TITLE
Fill missing data and products to MongoDB.

### ISSUE THREAD

**Issue by nikolas-joyce** [TMQR/SG#5]
We have not had access to IQfeed since end of Sept/Oct. Need to backfill existing futures products.

**Comment by alexveden** [comment]
1. Which datafeed should I use? IQFeed?
2. Do you need both v1 and v2 data to be updated?
3. Also we need metadata updates as well, I wondering about the source.

**Comment by nikolas-joyce** [comment]
We could use IQfeed. What metadata do we require. Could we get the metadata from quantgo? Where did we get the metadata from before?

Sent from my iPhone

On Jan 23, 2019, at 1:37 AM, Aleksandr Vedeneev <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Which datafeed should I use? IQFeed?
  2.  Do you need both v1 and v2 data to be updated?
  3.  Also we need metadata updates as well, I wondering about the source.

**Comment by alexveden** [comment]
In case of iqfeed we should already have metadata scripts. Metadata is information about contract expiration, strikes, etc--Best regards, Alex16:57, 23 января 2019 г., NikolasJoyce <notifications@github.com>:We could use IQfeed. What metadata do we require. Could we get the metadata from quantgo? Where did we get the metadata from before?



Sent from my iPhone



On Jan 23, 2019, at 1:37 AM, Aleksandr Vedeneev <notifications@github.com<mailto:notifications@github.com>> wrote:





  1.  Which datafeed should I use? IQFeed?

  2.  Do you need both v1 and v2 data to be updated?

  3.  Also we need metadata updates as well, I wondering about the source.

**Comment by nikolas-joyce** [comment]
I will look into getting iqfeed again.

Sent from my iPhone

On Jan 23, 2019, at 5:06 AM, Aleksandr Vedeneev <notifications@github.com<mailto:notifications@github.com>> wrote:

In case of iqfeed we should already have metadata scripts. Metadata is information about contract expiration, strikes, etc--Best regards, Alex16:57, 23 января 2019 г., NikolasJoyce <notifications@github.com<mailto:notifications@github.com>>:We could use IQfeed. What metadata do we require. Could we get the metadata from quantgo? Where did we get the metadata from before?



Sent from my iPhone



On Jan 23, 2019, at 1:37 AM, Aleksandr Vedeneev <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:





1. Which datafeed should I use? IQFeed?

2. Do you need both v1 and v2 data to be updated?

3. Also we need metadata updates as well, I wondering about the source.
